django-oscar-master/src/oscar/apps/voucher/models.py
from oscar.apps.voucher.abstract_models import (
    AbstractVoucher,
    AbstractVoucherApplication,
    AbstractVoucherSet,
)
from oscar.core.loading import is_model_registered

__all__ = []

if not is_model_registered("voucher", "VoucherSet"):

    class VoucherSet(AbstractVoucherSet):
        pass

    __all__.append("VoucherSet")


if not is_model_registered("voucher", "Voucher"):

    class Voucher(AbstractVoucher):
        pass

    __all__.append("Voucher")


if not is_model_registered("voucher", "VoucherApplication"):

    class VoucherApplication(AbstractVoucherApplication):
        pass

    __all__.append("VoucherApplication")

django-oscar-master/src/oscar/apps/dashboard/communications/forms.py
from django import forms
from django.template import Template, TemplateSyntaxError
from django.utils.translation import gettext_lazy as _

from oscar.apps.customer.utils import normalise_email
from oscar.core.loading import get_model

CommunicationEventType = get_model("communication", "CommunicationEventType")
Order = get_model("order", "Order")


class CommunicationEventTypeForm(forms.ModelForm):
    email_subject_template = forms.CharField(label=_("Email subject template"))
    email_body_template = forms.CharField(
        label=_("Email body text template"),
        required=True,
        widget=forms.widgets.Textarea(attrs={"class": "plain"}),
    )
    email_body_html_template = forms.CharField(
        label=_("Email body HTML template"), required=True, widget=forms.Textarea
    )

    preview_order_number = forms.CharField(label=_("Order number"), required=False)
    preview_email = forms.EmailField(label=_("Preview email"), required=False)

    # pylint: disable=attribute-defined-outside-init
    def __init__(self, *args, data=None, **kwargs):
        self.show_preview = False
        self.send_preview = False
        if data:
            self.show_preview = "show_preview" in data
            self.send_preview = "send_preview" in data
        super().__init__(data, *args, **kwargs)

    def validate_template(self, value):
        try:
            Template(value)
        except TemplateSyntaxError as e:
            raise forms.ValidationError(str(e))

    def clean_email_subject_template(self):
        subject = self.cleaned_data["email_subject_template"]
        self.validate_template(subject)
        return subject

    def clean_email_body_template(self):
        body = self.cleaned_data["email_body_template"]
        self.validate_template(body)
        return body

    def clean_email_body_html_template(self):
        body = self.cleaned_data["email_body_html_template"]
        self.validate_template(body)
        return body

    def clean_preview_order_number(self):
        number = self.cleaned_data["preview_order_number"].strip()
        if not self.instance.is_order_related():
            return number
        if not self.show_preview and not self.send_preview:
            return number
        try:
            self.preview_order = Order.objects.get(number=number)
        except Order.DoesNotExist:
            raise forms.ValidationError(_("No order found with this number"))
        return number

    def clean_preview_email(self):
        email = normalise_email(self.cleaned_data["preview_email"])
        if not self.send_preview:
            return email
        if not email:
            raise forms.ValidationError(_("Please enter an email address"))
        return email

    def get_preview_context(self):
        ctx = {}
        if hasattr(self, "preview_order"):
            ctx["order"] = self.preview_order
        return ctx

    class Meta:
        model = CommunicationEventType
        fields = [
            "name",
            "email_subject_template",
            "email_body_template",
            "email_body_html_template",
            "preview_order_number",
            "preview_email",
        ]

django-oscar-master/src/oscar/apps/dashboard/__init__.py
default_app_config = "oscar.apps.dashboard.apps.DashboardConfig"

django-oscar-master/src/oscar/apps/dashboard/catalogue/__init__.py
default_app_config = "oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig"

django-oscar-master/src/oscar/apps/dashboard/catalogue/views.py
# pylint: disable=attribute-defined-outside-init
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_tables2 import SingleTableMixin, SingleTableView

from oscar.core.loading import get_class, get_classes, get_model
from oscar.views.generic import ObjectLookupView

(
    ProductForm,
    ProductClassSelectForm,
    ProductSearchForm,
    ProductClassForm,
    CategoryForm,
    StockAlertSearchForm,
    AttributeOptionGroupForm,
    OptionForm,
) = get_classes(
    "dashboard.catalogue.forms",
    (
        "ProductForm",
        "ProductClassSelectForm",
        "ProductSearchForm",
        "ProductClassForm",
        "CategoryForm",
        "StockAlertSearchForm",
        "AttributeOptionGroupForm",
        "OptionForm",
    ),
)
(
    StockRecordFormSet,
    ProductCategoryFormSet,
    ProductImageFormSet,
    ProductRecommendationFormSet,
    ProductAttributesFormSet,
    AttributeOptionFormSet,
) = get_classes(
    "dashboard.catalogue.formsets",
    (
        "StockRecordFormSet",
        "ProductCategoryFormSet",
        "ProductImageFormSet",
        "ProductRecommendationFormSet",
        "ProductAttributesFormSet",
        "AttributeOptionFormSet",
    ),
)
ProductTable, CategoryTable, AttributeOptionGroupTable, OptionTable = get_classes(
    "dashboard.catalogue.tables",
    ("ProductTable", "CategoryTable", "AttributeOptionGroupTable", "OptionTable"),
)
(PopUpWindowCreateMixin, PopUpWindowUpdateMixin, PopUpWindowDeleteMixin) = get_classes(
    "dashboard.views",
    ("PopUpWindowCreateMixin", "PopUpWindowUpdateMixin", "PopUpWindowDeleteMixin"),
)
PartnerProductFilterMixin = get_class(
    "dashboard.catalogue.mixins", "PartnerProductFilterMixin"
)
Product = get_model("catalogue", "Product")
Category = get_model("catalogue", "Category")
ProductImage = get_model("catalogue", "ProductImage")
ProductCategory = get_model("catalogue", "ProductCategory")
ProductClass = get_model("catalogue", "ProductClass")
StockRecord = get_model("partner", "StockRecord")
StockAlert = get_model("partner", "StockAlert")
Partner = get_model("partner", "Partner")
AttributeOptionGroup = get_model("catalogue", "AttributeOptionGroup")
Option = get_model("catalogue", "Option")


class ProductListView(PartnerProductFilterMixin, SingleTableView):
    """
    Dashboard view of the product list.
    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_list.html"
    form_class = ProductSearchForm
    productclass_form_class = ProductClassSelectForm
    table_class = ProductTable
    context_table_name = "products"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["form"] = self.form
        ctx["productclass_form"] = self.productclass_form_class()
        return ctx

    def get_description(self, form):
        if form.is_valid() and any(form.cleaned_data.values()):
            return _("Product search results")
        return _("Products")

    def get_table(self, **kwargs):
        if "recently_edited" in self.request.GET:
            kwargs.update(dict(orderable=False))

        table = super().get_table(**kwargs)
        table.caption = self.get_description(self.form)
        return table

    def get_table_pagination(self, table):
        return dict(per_page=settings.OSCAR_DASHBOARD_ITEMS_PER_PAGE)

    def get_queryset(self):
        """
        Build the queryset for this list
        """
        queryset = Product.objects.browsable_dashboard().base_queryset()
        queryset = self.filter_queryset(queryset)
        queryset = self.apply_search(queryset)
        return queryset

    def apply_search(self, queryset):
        """
        Search through the filtered queryset.

        We must make sure that we don't return search results that the user is not allowed
        to see (see filter_queryset).
        """
        self.form = self.form_class(self.request.GET)

        if not self.form.is_valid():
            return queryset

        data = self.form.cleaned_data

        upc = data.get("upc")
        if upc:
            # Filter the queryset by upc
            # For usability reasons, we first look at exact matches and only return
            # them if there are any. Otherwise we return all results
            # that contain the UPC.

            # Look up all matches (child products, products not allowed to access) ...
            matches_upc = Product.objects.filter(
                Q(upc__iexact=upc) | Q(children__upc__iexact=upc)
            )

            # ... and use that to pick all standalone or parent products that the user is
            # allowed to access.
            qs_match = queryset.filter(
                Q(id__in=matches_upc.values("id"))
                | Q(id__in=matches_upc.values("parent_id"))
            )

            if qs_match.exists():
                # If there's a direct UPC match, return just that.
                queryset = qs_match
            else:
                # No direct UPC match. Let's try the same with an icontains search.
                matches_upc = Product.objects.filter(
                    Q(upc__icontains=upc) | Q(children__upc__icontains=upc)
                )
                queryset = queryset.filter(
                    Q(id__in=matches_upc.values("id"))
                    | Q(id__in=matches_upc.values("parent_id"))
                )

        title = data.get("title")
        if title:
            queryset = queryset.filter(
                Q(title__icontains=title) | Q(children__title__icontains=title)
            )

        return queryset.distinct()


class ProductCreateRedirectView(generic.RedirectView):
    permanent = False
    productclass_form_class = ProductClassSelectForm

    def get_product_create_url(self, product_class):
        """Allow site to provide custom URL"""
        return reverse(
            "dashboard:catalogue-product-create",
            kwargs={"product_class_slug": product_class.slug},
        )

    def get_invalid_product_class_url(self):
        messages.error(self.request, _("Please choose a product type"))
        return reverse("dashboard:catalogue-product-list")

    def get_redirect_url(self, *args, **kwargs):
        form = self.productclass_form_class(self.request.GET)
        if form.is_valid():
            product_class = form.cleaned_data["product_class"]
            return self.get_product_create_url(product_class)

        else:
            return self.get_invalid_product_class_url()


class ProductCreateUpdateView(PartnerProductFilterMixin, generic.UpdateView):
    """
    Dashboard view that is can both create and update products of all kinds.
    It can be used in three different ways, each of them with a unique URL
    pattern:
    - When creating a new standalone product, this view is called with the
      desired product class
    - When editing an existing product, this view is called with the product's
      primary key. If the product is a child product, the template considerably
      reduces the available form fields.
    - When creating a new child product, this view is called with the parent's
      primary key.

    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_update.html"
    model = Product
    context_object_name = "product"

    form_class = ProductForm
    category_formset = ProductCategoryFormSet
    image_formset = ProductImageFormSet
    recommendations_formset = ProductRecommendationFormSet
    stockrecord_formset = StockRecordFormSet

    creating = False
    parent = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formsets = {
            "category_formset": self.category_formset,
            "image_formset": self.image_formset,
            "recommended_formset": self.recommendations_formset,
            "stockrecord_formset": self.stockrecord_formset,
        }

    def dispatch(self, request, *args, **kwargs):
        resp = super().dispatch(request, *args, **kwargs)
        return self.check_objects_or_redirect() or resp

    def check_objects_or_redirect(self):
        """
        Allows checking the objects fetched by get_object and redirect
        if they don't satisfy our needs.
        Is used to redirect when create a new variant and the specified
        parent product can't actually be turned into a parent product.
        """
        if self.creating and self.parent is not None:
            is_valid, reason = self.parent.can_be_parent(give_reason=True)
            if not is_valid:
                messages.error(self.request, reason)
                return redirect("dashboard:catalogue-product-list")

    def get_queryset(self):
        """
        Filter products that the user doesn't have permission to update
        """
        return self.filter_queryset(Product.objects.all())

    def get_object(self, queryset=None):
        """
        This parts allows generic.UpdateView to handle creating products as
        well. The only distinction between an UpdateView and a CreateView
        is that self.object is None. We emulate this behavior.

        This method is also responsible for setting self.product_class and
        self.parent.
        """
        self.creating = "pk" not in self.kwargs
        if self.creating:
            # Specifying a parent product is only done when creating a child
            # product.
            parent_pk = self.kwargs.get("parent_pk")
            if parent_pk is None:
                self.parent = None
                # A product class needs to be specified when creating a

django-oscar-master/src/oscar/apps/dashboard/communications/__init__.py
default_app_config = (
    "oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig"
)

django-oscar-master/src/oscar/apps/dashboard/communications/views.py
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template import TemplateSyntaxError
from django.utils.translation import gettext_lazy as _
from django.views import generic

from oscar.core.loading import get_class, get_model

CommunicationEventType = get_model("communication", "CommunicationEventType")
CommunicationEventTypeForm = get_class(
    "dashboard.communications.forms", "CommunicationEventTypeForm"
)
Dispatcher = get_class("communication.utils", "Dispatcher")


class ListView(generic.ListView):
    model = CommunicationEventType
    template_name = "oscar/dashboard/comms/list.html"
    context_object_name = "commtypes"


class UpdateView(generic.UpdateView):
    model = CommunicationEventType
    form_class = CommunicationEventTypeForm
    template_name = "oscar/dashboard/comms/detail.html"
    context_object_name = "commtype"
    success_url = "."
    slug_field = "code"

    def form_invalid(self, form):
        messages.error(
            self.request,
            _(
                "The submitted form was not valid, please correct "
                "the errors and resubmit"
            ),
        )
        return super().form_invalid(form)

    def form_valid(self, form):
        if "send_preview" in self.request.POST:
            return self.send_preview(form)
        if "show_preview" in self.request.POST:
            return self.show_preview(form)
        messages.success(self.request, _("Email saved"))
        return super().form_valid(form)

    def get_messages_context(self, form):
        ctx = {"user": self.request.user, "site": get_current_site(self.request)}
        ctx.update(form.get_preview_context())
        return ctx

    def show_preview(self, form):
        ctx = super().get_context_data()
        ctx["form"] = form

        commtype = form.save(commit=False)
        commtype_ctx = self.get_messages_context(form)
        try:
            msgs = commtype.get_messages(commtype_ctx)
        except TemplateSyntaxError as e:
            form.errors["__all__"] = form.error_class([str(e)])
            return self.render_to_response(ctx)

        ctx["show_preview"] = True
        ctx["preview"] = msgs
        return self.render_to_response(ctx)

    def send_preview(self, form):
        ctx = super().get_context_data()
        ctx["form"] = form

        commtype = form.save(commit=False)
        commtype_ctx = self.get_messages_context(form)
        try:
            msgs = commtype.get_messages(commtype_ctx)
        except TemplateSyntaxError as e:
            form.errors["__all__"] = form.error_class([str(e)])
            return self.render_to_response(ctx)

        email = form.cleaned_data["preview_email"]
        dispatch = Dispatcher()
        dispatch.send_email_messages(email, msgs)
        messages.success(self.request, _("A preview email has been sent to %s") % email)

        return self.render_to_response(ctx)

django-oscar-master/src/oscar/apps/dashboard/offers/__init__.py
default_app_config = "oscar.apps.dashboard.offers.apps.OffersDashboardConfig"

django-oscar-master/src/oscar/templates/oscar/dashboard/vouchers/voucher_delete.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% if not voucher.voucher_set %}
    {% blocktrans with name=voucher.name %}Delete voucher '{{ name }}'?{% endblocktrans %} | {% trans "Vouchers" %} | {{ block.super }}
    {% else %}
    {% blocktrans with code=voucher.code %}Delete voucher '{{ code }}'?{% endblocktrans %} | {% trans "Vouchers" %} | {{ block.super }}
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-stats' pk=voucher.pk %}">{{ voucher }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{% trans "Delete?" %}</li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}
    {% if not voucher.voucher_set %}
    {% blocktrans with name=voucher.name %}Delete voucher '{{ name }}'?{% endblocktrans %}
    {% else %}
    {% blocktrans with code=voucher.code %}Delete voucher '{{ code }}' from set?{% endblocktrans %}
    {% endif %}
{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Voucher details" %}</h2>
    </div>
    <div class="card card-body bg-light">
        {% include "oscar/dashboard/vouchers/partials/voucher_details_table.html" %}
        <form method="post">
            {% csrf_token %}
            <div class="form-actions">
                <button class="btn btn-danger" type="submit" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button> {% trans "or" %}
                <a href="{% if not voucher.voucher_set %}{% url 'dashboard:voucher-list' %}{% else %}{% url 'dashboard:voucher-set-detail' pk=voucher.voucher_set.pk %}{% endif %}">{% trans "cancel" %}</a>
            </div>
        </form>
    </div>
{% endblock dashboard_content %}

django-oscar-master/src/oscar/templates/oscar/dashboard/vouchers/voucher_detail.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block title %}
    {{ voucher }} | {% trans "Vouchers" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-list' %}">{% trans "Vouchers" %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ voucher }}</li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}
    {{ voucher }}
{% endblock %}

{% block dashboard_content %}

    <div class="table-header">
        <h2>{% trans "Voucher details" %}</h2>
    </div>
    {% include "oscar/dashboard/vouchers/partials/voucher_details_table.html" %}

    <div class="table-header">
        <h2>{% trans "Attached offers" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        {% if voucher.offers.exists %}
        <thead>
            <tr>
                <th>{% trans "Offer name" %}</th>
                <th>{% trans "Start date" %}</th>
                <th>{% trans "End date" %}</th>
                <th>{% trans "Is available?" %}</th>
                <th>{% trans "Priority" %}</th>
                <th>{% trans "Incentive" %}</th>
                <th>{% trans "Condition" %}</th>
                <th>{% trans "Restrictions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for offer in voucher.offers.all %}
            <tr>
                <td>
                    <a href="{% url 'dashboard:offer-detail' pk=offer.pk %}">{{ offer.name }}</a>
                </td>
                <td>{{ offer.start_datetime|default:"-" }}</td>
                <td>{{ offer.end_datetime|default:"-" }}</td>
                <td>{% if offer.is_available %}
                    <span class="badge badge-success">{% trans "Yes" %}</span>
                    {% else %}
                    <span class="badge badge-danger">{% trans "No" %}</span>
                    {% endif %}
                </td>
                <td>{{ offer.priority }}</td>
                <td>{{ offer.benefit.description|safe }}</td>
                <td>{{ offer.condition.description|safe }}</td>
                <td>
                    {% for restriction in offer.availability_restrictions %}
                    {% if not restriction.is_satisfied %}
                    <label class="badge badge-danger">
                        {{ restriction.description }}
                    </label>
                    {% else %}
                    {{ restriction.description }}<br/>
                    {% endif %}
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
        {% else %}
        <tr>
            <td>{% trans "No offers are attached to this voucher." %}</td>
        </tr>
        {% endif %}
    </table>

    <div class="table-header">
        <h2>{% trans "Voucher performance" %}</h2>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tbody>
            <tr><th>{% trans "Number of basket additions" %}</th><td>{{ voucher.num_basket_additions }}</td></tr>
            <tr><th>{% trans "Number of orders" %}</th><td>{{ voucher.num_orders }}</td></tr>
            <tr><th>{% trans "Total discount" %}</th><td>{{ voucher.total_discount|currency }}</td></tr>
        </tbody>
    </table>

    <div class="table-header">
        <h2>{% trans "Recent orders" %}</h2>
    </div>

    <table class="table table-striped table-bordered table-hover">
        {% if not discounts %}
            <tr><td>{% trans "No orders have been placed that use this voucher." %}</td></tr>
        {% else %}
            <thead>
                <tr>
                    <th>{% trans "Order number" %}</th>
                    <th>{% trans "Order total" %}</th>
                    <th>{% trans "Discount" %}</th>
                    <th>{% trans "Date placed" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for discount in discounts %}
                    {% with order=discount.order %}
                        <tr>
                            <td><a href="{% url "dashboard:order-detail" number=order.number %}">{{ order.number }}</a></td>
                            <td>{{ order.total_incl_tax|currency:order.currency }}</td>
                            <td>{{ discount.amount|currency:order.currency }}</td>
                            <td>{{ order.date_placed }}</td>
                        </tr>
                    {% endwith %}
                {% endfor %}
            </tbody>
        {% endif %}
    </table>

    <div class="form-actions">
        {% if not voucher.voucher_set %}
        <a class="btn btn-primary" href="{% url 'dashboard:voucher-update' pk=voucher.id %}">{% trans "Edit" %}</a> {% trans "or" %}
        {% else %}
        <a class="btn btn-primary" href="{% url 'dashboard:voucher-set-update' pk=voucher.voucher_set.pk %}">{% trans "Edit set" %}</a> {% trans "or" %}
        {% endif %}
        <a class="btn btn-danger" href="{% url 'dashboard:voucher-delete' pk=voucher.id %}">
        {% if not voucher.voucher_set %}
        {% trans "Delete" %}
        {% else %}
        {% trans "Delete from set" %}
        {% endif %}
        </a> {% trans "or" %}
        <a href="{% if not voucher.voucher_set %}{% url 'dashboard:voucher-list' %}{% else %}{% url 'dashboard:voucher-set-detail' pk=voucher.voucher_set.pk %}{% endif %}">{% trans "cancel" %}</a>
    </div>

{% endblock dashboard_content %}

django-oscar-master/src/oscar/templates/oscar/dashboard/vouchers/voucher_set_delete.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {% blocktrans with name=voucher_set.name %}Delete voucher set '{{ name }}'?{% endblocktrans %} | {% trans "Voucher sets" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-set-list' %}">{% trans "Voucher sets" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-set-detail' pk=voucher_set.pk %}">{{ voucher_set }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{% trans "Delete?" %}</li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}
    {% blocktrans with name=voucher_set.name count=voucher_set.count %}Delete voucher set '{{ name }}' and its {{ count }} vouchers?{% endblocktrans %}
{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2>{% trans "Voucher set details" %}</h2>
    </div>
    <div class="card card-body bg-light">
        {% include "oscar/dashboard/vouchers/partials/voucher_set_details_table.html" %}
        <form method="post">
            {% csrf_token %}
            <div class="form-actions">
                <button class="btn btn-danger" type="submit" data-loading-text="{% trans 'Deleting...' %}">{% trans "Delete" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-set-list' %}">{% trans "cancel" %}</a>
            </div>
        </form>
    </div>
{% endblock dashboard_content %}

django-oscar-master/src/oscar/templates/oscar/dashboard/vouchers/voucher_set_form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load currency_filters %}
{% load i18n %}

{% block body_class %}{{ block.super }} create-page{% endblock %}

{% block title %}
    {{ title }} | {% trans "Voucher sets" %} | {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a></li>
            <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-list' %}">{% trans "Voucher sets" %}</a></li>
            {% if voucher_set %}
                <li class="breadcrumb-item"><a href="{% url 'dashboard:voucher-set-detail' pk=voucher_set.pk %}">{{ voucher_set }}</a></li>
            {% endif %}
            <li class="breadcrumb-item active" aria-current="page">{% trans "Edit" %}</li>
        </ol>
    </nav>
{% endblock %}

{% block headertext %}{{ title }}{% endblock %}

{% block dashboard_content %}
    <div class="table-header">
        <h2><i class="fas fa-money-bill"></i>
            {% if voucher_set %}
                {% trans "Edit voucher set" %}
            {% else %}
                {% trans "Create voucher set" %}
            {% endif %}
        </h2>
    </div>
    <form method="post" class="card card-body form-stacked">
        {% csrf_token %}
        {% include "oscar/dashboard/partials/form_fields.html" with form=form %}
        {% block form_actions %}
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">{% trans "Save" %}</button> {% trans "or" %}
                <a href="{% url 'dashboard:voucher-set-list' %}">{% trans "cancel" %}</a>
            </div>
        {% endblock form_actions %}
    </form>
{% endblock dashboard_content %}